apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend-api

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: backend-api

    spec:
      containers:
        - name: backend

          image: 090565618799.dkr.ecr.us-east-1.amazonaws.com/lms-backend:d0f0f54

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

          env:
            - name: PORT
              value: "5000"

            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGODB_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET

            - name: USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_EMAIL

            - name: USER_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: USER_EMAIL_PASSWORD

            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_CLOUD_NAME

            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_API_KEY

            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: CLOUDINARY_API_SECRET

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STRIPE_API_KEY

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: STRIPE_SECRET_KEY