version: "3.9"

services:
  backend:
    build: ./backend
    container_name: lms-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend/ai-lms
    container_name: lms-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/ai-lms/.env.local
    depends_on:
      - backend